# Generated by Django 4.2.9 on 2025-01-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_deleted_at_chatmessage_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_deleted',
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'recipient', 'timestamp'], name='chat_chatme_sender__921695_idx'),
        ),
    ]
